export interface BrowserCookieExport {
  name: string;
  value: string;
  domain: string;
  path?: string;
  expirationDate?: number;
  hostOnly?: boolean;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: string;
}

/** Domains used to filter extension JSON exports per site adapter. */
export const SITE_COOKIE_DOMAINS: Record<string, string[]> = {
  pornhub: ["pornhub.com"],
  xhamster: ["xhamster.com", "xhamster.desi", "xhamster.one"],
  xvideos: ["xvideos.com"],
  thisvid: ["thisvid.com"],
};

export const COOKIE_EXTENSION_URL =
  "https://chromewebstore.google.com/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm";

export const COOKIE_IMPORT_STEPS = [
  "Option A — Cookie-Editor extension: install, log in on the site, Export → JSON.",
  "Option B — DevTools (no extension): F12 → Application → Cookies → select domain → copy table rows → paste below → Import DevTools table.",
  "Option C — Console on the site tab: run the copy(JSON.stringify(...)) snippet from docs, paste JSON below.",
  "Select the matching site, paste, then Import JSON or Import DevTools table.",
];

/** One-liner to run in the browser console while logged in on the target site. */
export const DEVTOOLS_COOKIE_CONSOLE_SNIPPET = `copy(JSON.stringify(document.cookie.split("; ").map(p=>{const i=p.indexOf("=");return{name:p.slice(0,i),value:p.slice(i+1),domain:location.hostname,path:"/"}}),null,2))`;

function parseIsoExpiry(value: string): number | undefined {
  const trimmed = value.trim();
  if (!trimmed || trimmed.toLowerCase() === "session") return undefined;
  const ms = Date.parse(trimmed);
  if (Number.isNaN(ms)) return undefined;
  return Math.floor(ms / 1000);
}

function isTruthyCell(value: string | undefined): boolean {
  if (!value) return false;
  const v = value.trim().toLowerCase();
  return v === "✓" || v === "true" || v === "yes" || v === "1";
}

/** Parse cookies copied from Chrome/Edge DevTools Application → Cookies table (TSV). */
export function parseDevToolsCookieTable(raw: string): BrowserCookieExport[] {
  const cookies: BrowserCookieExport[] = [];
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("Name\t") || trimmed.startsWith("#")) continue;
    const parts = trimmed.split("\t");
    if (parts.length < 4) continue;
    const [name, value, domain, path, expires, , httpOnly, secure] = parts;
    if (!name || value === undefined || !domain) continue;
    cookies.push({
      name,
      value,
      domain,
      path: path || "/",
      expirationDate: expires ? parseIsoExpiry(expires) : undefined,
      hostOnly: !domain.startsWith("."),
      httpOnly: isTruthyCell(httpOnly),
      secure: isTruthyCell(secure),
    });
  }
  return cookies;
}

export function importCookiesFromDevToolsTable(raw: string, siteId: string): string {
  const cookies = filterCookiesForSite(parseDevToolsCookieTable(raw), siteId);
  if (cookies.length === 0) {
    throw new Error("No cookies parsed. Copy rows from DevTools Application → Cookies.");
  }
  return jsonToNetscape(cookies);
}

export function jsonToNetscape(cookies: BrowserCookieExport[]): string {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by ArcHive",
    "# https://curl.haxx.se/rfc/cookie_spec.html",
    "",
  ];

  for (const cookie of cookies) {
    if (!cookie.name || cookie.value === undefined) continue;
    const domain = cookie.domain.startsWith(".") ? cookie.domain : `.${cookie.domain}`;
    const includeSubdomains = cookie.hostOnly ? "FALSE" : "TRUE";
    const path = cookie.path || "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
    lines.push(
      `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`,
    );
  }

  return lines.join("\n");
}

export function parseCookieJson(raw: string): BrowserCookieExport[] {
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error("Cookie JSON must be an array");
  }
  return parsed as BrowserCookieExport[];
}

export function filterCookiesForSite(
  cookies: BrowserCookieExport[],
  siteId: string,
): BrowserCookieExport[] {
  const domains = SITE_COOKIE_DOMAINS[siteId];
  if (!domains?.length) return cookies;
  return cookies.filter((cookie) => domains.some((domain) => cookie.domain.includes(domain)));
}

export function importCookiesFromJson(raw: string, siteId: string): string {
  const cookies = filterCookiesForSite(parseCookieJson(raw), siteId);
  if (cookies.length === 0) {
    throw new Error("No cookies matched this site. Check domain filters or site selection.");
  }
  return jsonToNetscape(cookies);
}

/** Bookmarklet opens the site login page; user exports JSON via Cookie-Editor. */
export function buildCookieBookmarklet(siteUrl: string): string {
  const target = siteUrl.replace(/"/g, "%22");
  return `javascript:(function(){window.open("${target}","_blank");alert("1) Log in on this tab\\n2) Open Cookie-Editor → Export → JSON\\n3) Paste JSON in ArcHive Settings → Cookies");})();`;
}
