export interface BrowserCookieExport {
  name: string;
  value: string;
  domain: string;
  path?: string;
  expirationDate?: number;
  hostOnly?: boolean;
  httpOnly?: boolean;
  secure?: boolean;
  sameSite?: string;
}

/** Domains used to filter extension JSON exports per site adapter. */
export const SITE_COOKIE_DOMAINS: Record<string, string[]> = {
  pornhub: ["pornhub.com"],
  xhamster: ["xhamster.com", "xhamster.desi", "xhamster.one"],
  xvideos: ["xvideos.com"],
  thisvid: ["thisvid.com"],
};

export const COOKIE_EXTENSION_URL =
  "https://chromewebstore.google.com/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm";

export const COOKIE_IMPORT_STEPS = [
  "Install the Cookie-Editor extension (Chrome/Edge/Firefox).",
  "Log in on the target site in your browser.",
  "Open Cookie-Editor → Export → JSON → copy to clipboard.",
  "Paste JSON below and click Import JSON.",
];

export function jsonToNetscape(cookies: BrowserCookieExport[]): string {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by ArcHive",
    "# https://curl.haxx.se/rfc/cookie_spec.html",
    "",
  ];

  for (const cookie of cookies) {
    if (!cookie.name || cookie.value === undefined) continue;
    const domain = cookie.domain.startsWith(".") ? cookie.domain : `.${cookie.domain}`;
    const includeSubdomains = cookie.hostOnly ? "FALSE" : "TRUE";
    const path = cookie.path || "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
    lines.push(
      `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`,
    );
  }

  return lines.join("\n");
}

export function parseCookieJson(raw: string): BrowserCookieExport[] {
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error("Cookie JSON must be an array");
  }
  return parsed as BrowserCookieExport[];
}

export function filterCookiesForSite(
  cookies: BrowserCookieExport[],
  siteId: string,
): BrowserCookieExport[] {
  const domains = SITE_COOKIE_DOMAINS[siteId];
  if (!domains?.length) return cookies;
  return cookies.filter((cookie) => domains.some((domain) => cookie.domain.includes(domain)));
}

export function importCookiesFromJson(raw: string, siteId: string): string {
  const cookies = filterCookiesForSite(parseCookieJson(raw), siteId);
  if (cookies.length === 0) {
    throw new Error("No cookies matched this site. Check domain filters or site selection.");
  }
  return jsonToNetscape(cookies);
}

/** Bookmarklet opens the site login page; user exports JSON via Cookie-Editor. */
export function buildCookieBookmarklet(siteUrl: string): string {
  const target = siteUrl.replace(/"/g, "%22");
  return `javascript:(function(){window.open("${target}","_blank");alert("1) Log in on this tab\\n2) Open Cookie-Editor → Export → JSON\\n3) Paste JSON in ArcHive Settings → Cookies");})();`;
}
