import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dir, "..");
const PLUGINS_DIR = path.join(ROOT, "plugins");
const OUT_FILE = path.join(ROOT, "src/lib/plugins/registry.generated.ts");

interface PluginManifest {
  id: string;
  name: string;
  version: string;
  entry: string;
}

async function listPluginDirs(): Promise<string[]> {
  try {
    const entries = await readdir(PLUGINS_DIR, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
      .map((entry) => entry.name);
  } catch {
    return [];
  }
}

async function main(): Promise<void> {
  const dirs = await listPluginDirs();
  const plugins: { dir: string; manifest: PluginManifest }[] = [];

  for (const dir of dirs) {
    const manifestPath = path.join(PLUGINS_DIR, dir, "plugin.json");
    try {
      const raw = await readFile(manifestPath, "utf8");
      const manifest = JSON.parse(raw) as PluginManifest;
      if (!manifest.id || !manifest.entry) {
        console.warn(`Skipping ${dir}: plugin.json missing id or entry`);
        continue;
      }
      plugins.push({ dir, manifest });
    } catch {
      continue;
    }
  }

  const imports = plugins
    .map((p, i) => {
      const entry = p.manifest.entry.replace(/\.tsx?$/, "");
      const importPath = `../../../plugins/${p.dir}/${entry}`;
      return `import plugin${i} from "${importPath}";`;
    })
    .join("\n");

  const registry = plugins.map((p, i) => `  plugin${i},`).join("\n");

  const content = `// Auto-generated by scripts/generate-plugins.ts — do not edit.
${imports ? `${imports}\n` : ""}
import type { ArcHivePlugin } from "./types";

const PLUGINS: ArcHivePlugin[] = [
${registry}
];

export function getRegisteredPlugins(): ArcHivePlugin[] {
  return PLUGINS;
}
`;

  await writeFile(OUT_FILE, content, "utf8");
  console.log(`Generated ${OUT_FILE} (${plugins.length} plugin(s))`);
}

await main();
