/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as BrowseCustomRouteImport } from './routes/browse/custom'
import { Route as LibraryTagsIndexRouteImport } from './routes/library/tags/index'
import { Route as LibraryScenesIndexRouteImport } from './routes/library/scenes/index'
import { Route as LibraryPerformersIndexRouteImport } from './routes/library/performers/index'
import { Route as BrowseSiteIndexRouteImport } from './routes/browse/$site/index'
import { Route as BrowseSiteKindSlugRouteImport } from './routes/browse/$site/$kind/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCustomRoute = BrowseCustomRouteImport.update({
  id: '/browse/custom',
  path: '/browse/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryTagsIndexRoute = LibraryTagsIndexRouteImport.update({
  id: '/library/tags/',
  path: '/library/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryScenesIndexRoute = LibraryScenesIndexRouteImport.update({
  id: '/library/scenes/',
  path: '/library/scenes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPerformersIndexRoute = LibraryPerformersIndexRouteImport.update({
  id: '/library/performers/',
  path: '/library/performers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSiteIndexRoute = BrowseSiteIndexRouteImport.update({
  id: '/browse/$site/',
  path: '/browse/$site/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSiteKindSlugRoute = BrowseSiteKindSlugRouteImport.update({
  id: '/browse/$site/$kind/$slug',
  path: '/browse/$site/$kind/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse/custom': typeof BrowseCustomRoute
  '/browse/': typeof BrowseIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/browse/$site/': typeof BrowseSiteIndexRoute
  '/library/performers/': typeof LibraryPerformersIndexRoute
  '/library/scenes/': typeof LibraryScenesIndexRoute
  '/library/tags/': typeof LibraryTagsIndexRoute
  '/browse/$site/$kind/$slug': typeof BrowseSiteKindSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse/custom': typeof BrowseCustomRoute
  '/browse': typeof BrowseIndexRoute
  '/downloads': typeof DownloadsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/browse/$site': typeof BrowseSiteIndexRoute
  '/library/performers': typeof LibraryPerformersIndexRoute
  '/library/scenes': typeof LibraryScenesIndexRoute
  '/library/tags': typeof LibraryTagsIndexRoute
  '/browse/$site/$kind/$slug': typeof BrowseSiteKindSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse/custom': typeof BrowseCustomRoute
  '/browse/': typeof BrowseIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/browse/$site/': typeof BrowseSiteIndexRoute
  '/library/performers/': typeof LibraryPerformersIndexRoute
  '/library/scenes/': typeof LibraryScenesIndexRoute
  '/library/tags/': typeof LibraryTagsIndexRoute
  '/browse/$site/$kind/$slug': typeof BrowseSiteKindSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse/custom'
    | '/browse/'
    | '/downloads/'
    | '/settings/'
    | '/browse/$site/'
    | '/library/performers/'
    | '/library/scenes/'
    | '/library/tags/'
    | '/browse/$site/$kind/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse/custom'
    | '/browse'
    | '/downloads'
    | '/settings'
    | '/browse/$site'
    | '/library/performers'
    | '/library/scenes'
    | '/library/tags'
    | '/browse/$site/$kind/$slug'
  id:
    | '__root__'
    | '/'
    | '/browse/custom'
    | '/browse/'
    | '/downloads/'
    | '/settings/'
    | '/browse/$site/'
    | '/library/performers/'
    | '/library/scenes/'
    | '/library/tags/'
    | '/browse/$site/$kind/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseCustomRoute: typeof BrowseCustomRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  BrowseSiteIndexRoute: typeof BrowseSiteIndexRoute
  LibraryPerformersIndexRoute: typeof LibraryPerformersIndexRoute
  LibraryScenesIndexRoute: typeof LibraryScenesIndexRoute
  LibraryTagsIndexRoute: typeof LibraryTagsIndexRoute
  BrowseSiteKindSlugRoute: typeof BrowseSiteKindSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads/'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/custom': {
      id: '/browse/custom'
      path: '/browse/custom'
      fullPath: '/browse/custom'
      preLoaderRoute: typeof BrowseCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/tags/': {
      id: '/library/tags/'
      path: '/library/tags'
      fullPath: '/library/tags/'
      preLoaderRoute: typeof LibraryTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/scenes/': {
      id: '/library/scenes/'
      path: '/library/scenes'
      fullPath: '/library/scenes/'
      preLoaderRoute: typeof LibraryScenesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/performers/': {
      id: '/library/performers/'
      path: '/library/performers'
      fullPath: '/library/performers/'
      preLoaderRoute: typeof LibraryPerformersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$site/': {
      id: '/browse/$site/'
      path: '/browse/$site'
      fullPath: '/browse/$site/'
      preLoaderRoute: typeof BrowseSiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$site/$kind/$slug': {
      id: '/browse/$site/$kind/$slug'
      path: '/browse/$site/$kind/$slug'
      fullPath: '/browse/$site/$kind/$slug'
      preLoaderRoute: typeof BrowseSiteKindSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseCustomRoute: BrowseCustomRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  BrowseSiteIndexRoute: BrowseSiteIndexRoute,
  LibraryPerformersIndexRoute: LibraryPerformersIndexRoute,
  LibraryScenesIndexRoute: LibraryScenesIndexRoute,
  LibraryTagsIndexRoute: LibraryTagsIndexRoute,
  BrowseSiteKindSlugRoute: BrowseSiteKindSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
